import './globals.css';
import type { Metadata } from 'next';
import Script from 'next/script';
import { Open_Sans } from 'next/font/google';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script src="/static/theme.js" />
      </head>
      <body
        style={{ scrollBehavior: 'smooth' }}
        className={`${openSans.className} h-screen`}
      >
        {children}
      </body>
    </html>
  )
}
